#!/bin/bash

DEFINITION_FILE=elements_to_remove.toml
CONTENT_DIR=content
ZIP_FILE=replit-exam-lock.zip
[ ! $# -eq 0 ] && [ $1 = "-date" ] && ZIP_FILE=$(basename "$ZIP_FILE" .zip)-$(date +"%y%m%d%H%M%S").zip
[ ! $# -eq 0 ] && [ $1 = "-version" ] && ZIP_FILE=$(basename "$ZIP_FILE" .zip)-v$(grep -Po '"version\": "\K.*?(?=")' manifest.json).zip

[ -d "$CONTENT_DIR" ] && rm -r "$CONTENT_DIR"
mkdir "$CONTENT_DIR"

files=()

while read line; do
  case "$line" in
    \[*\]) file="$CONTENT_DIR"/"${line:1:-1}" &&
      files+=("$file") &&
      touch "$file";;
    \#\ *) echo "/* ${line#* } */" >> "$file";;
    ?*) echo "$line", >> "$file";;
  esac
done <$DEFINITION_FILE

for file in "${files[@]}"; do
  truncate -s-2 "$file"
  echo -e " {\n  display: none !important;\n}" >> "$file"
  echo "Built \"$file\" from definitions"
done

zip -qr "$ZIP_FILE" manifest.json LICENSE content/ icons/
echo "Zipped \"$ZIP_FILE\""
