# Tab bar, new tab "+" button
.css-b26pld

# Tab bar, extra option "..." button
.css-113zd6v

# Tab bar, right-click menu
.css-1o92kwk

# Editor, empty file AI generate prompt
.css-a3ac2g

# Editor, inline AI generate prompt
.css-1w3tfwx

# Editor, inline AI generate popup
.css-t5d0fj

# Editor, inline AI explain popup
.css-104vpr

# Editor, code highlight popup
.css-o1mq6

# Editor, bottom bar AI button
.css-14hsnor > .css-36v8q4:nth-of-type(1)

# Editor, bottom bar file type button
.css-14hsnor > .css-36v8q4:nth-of-type(2)

# Editor, right click menu, AI section
.css-1812gh1

# Editor, right click menu, Generate/Explain/Modify options
.css-s1go71[data-cy="context-menu-GenerateCode"]
.css-s1go71[data-cy="context-menu-ExplainCode"]
.css-s1go71[data-cy="context-menu-TransformCode"]

# Header, navigation menu overlay
.css-125g92

# Header, repl info overlay
.css-8zni13

# Header, repl resources overlay
.css-iuceai

# Header, top right section
.css-195num

# Left sidebar, Search
.css-10hnlfl

# Left sidebar, Tools
.css-1tosrz5 > .css-36v8q4:nth-of-type(2)

# Console, "Ask AI" button
.css-19c0wey

# Shell, inline AI generate prompt
.css-5hh8o6
